spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.109:3306/test
  data:
    redis:
      host: 192.168.1.109
      port: 6379
      database: 0
  security:
    jwt:
      secretkey: asdf
      expire: 7